### PR TITLE
Added Debian support

### PR DESCRIPTION
**Pull request by jkff**

### CODE REVIEW

**Comment by glarizza** [comment]
Hey there!  I've transferred this module to the Puppetlabs namespace, and we're actively working on it (and merging pull requests) there --> https://github.com/puppetlabs/puppetlabs-haproxy  Can you file this pull request there?  We would definitely appreciate it.  Thanks!

**Comment by jkff** [comment]
Thanks, done!

On Tue, Aug 28, 2012 at 7:00 PM, Gary Larizza notifications@github.comwrote:

> Hey there! I've transferred this module to the Puppetlabs namespace, and
> we're actively working on it (and merging pull requests) there -->
> https://github.com/puppetlabs/puppetlabs-haproxy Can you file this pull
> request there? We would definitely appreciate it. Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/glarizza/puppet-haproxy/pull/12#issuecomment-8113238.

## 

Eugene Kirpichov
http://www.linkedin.com/in/eugenekirpichov

**Comment by jkff** [comment]
Um, Gary, I rebased to puppetlabs-haproxy and now I'm getting exactly the same error as this guy: https://gist.github.com/3074101

**Comment by glarizza** [comment]
You might be using a newer version of the concat module in your test
harness - we're using the version from the Forge, so not the most recent
commit in Master (which, I believe, causes these issues).

On Tue, Aug 28, 2012 at 7:19 PM, Eugene Kirpichov
notifications@github.comwrote:

> Um, Gary, I rebased to puppetlabs-haproxy and now I'm getting exactly the
> same error as this guy: https://gist.github.com/3074101
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/glarizza/puppet-haproxy/pull/12#issuecomment-8113514.

## 

Gary Larizza
Professional Services Engineer
Puppet Labs

Join us for PuppetConf 2012 at the Mission Bay Convention Center in San
Francisco, California on September 27th and 28th --> http://bit.ly/pcsig12

**Comment by jkff** [comment]
Hm, but "rake spec" was checking out a concat module into spec/fixtures - wasn't it supposed to check out a correct version? Just to be sure, I removed my /etc/puppet/modules/haproxy to make sure it doesn't get in the way - nothing changed.

I mean - is this a bug of puppetlabs-haproxy (not checking out the proper concat for rake spec), or is it a problem with my environment?

**Comment by hunner** [comment]
@jkff I am also working on adding debian support based off of #7 :P. What I noticed is that the concat module has a `concat_basedir` custom fact which exports the value of `#{Puppet[:vardir]}/concat` so I just added a `:concat_basedir => '/dne'` value to my `:facts` rspec `let`.

Let me know if you make more progress with this! I'm also spending time on it today and will combine any changes you've pushed.

**Comment by jkff** [comment]
Oh, I'm stupid!! I forgot to copy the :concat_basedir part to the spec for Debian.

**Comment by jkff** [comment]
In any case, your pull request is more comprehensive, so I'm closing this one and pulling yours.

**Pull request closed without merging**
